### ISSUE TITLE
How do I get this to work?

### ISSUE THREAD

**Issue by zumpchke** [minrk/clingkernel#4]
How do I get this to work? (IPython newbie)

**Comment by jbcoe** [comment]
I got it working by setting up a virtual environment so that I could install packages without affecting my system Python setup. 

http://docs.python-guide.org/en/latest/dev/virtualenvs/

The virtualenv needs to use python 3 (so I found) and I found that will needed the following python modules installing from git (using python setup.py install):

https://github.com/minrk/clingkernel.git
https://github.com/ipython/ipykernel.git
https://github.com/ipython/ipython.git
https://github.com/ipython/ipython_genutils.git
https://github.com/jupyter/jupyter_client.git
https://github.com/jupyter/jupyter_core.git
https://github.com/jupyter/nbformat.git
https://github.com/jupyter/notebook.git
https://github.com/ipython/traitlets.git

You'll still need more modules installing:

Jinja2
MarkupSafe
decorator
jsonschema
pexpect
pickleshare
pyzmq
setuptools
simplegeneric
tornado
zmq

these can be installed using 

    pip install MODULENAME

I used a binary for cling downloaded from here:

https://root.cern.ch/drupal/content/cling-build-instructions

You need to define the environment variable CLING_EXE to be the path to your cling executable. It's probably worth running cling stand-alone from the console first to see that it works (It did so for me without problems).

That got things working for me. I'm not sure that all the modules above are necessary, I discovered what I needed by reading the missing module errors from cling-kernel crashes in ipython until things worked.

Entering

    ipython notebook

on the console and selecting a new C++ notebook should then get things working.

**Comment by zumpchke** [comment]
I got as far as being able to see a Python 3 kernel in IPython notebook -
but no C++. Any idea why this could be?

**Comment by WesternStar** [comment]
Make sure cling is in your path aliases don't count. On second thought make sure CLING_EXE is defined to you cling executable and avoid the whole problem.

**Comment by zumpchke** [comment]
I've gotten it to work. I had to copy cling/kernel.json to
~/.ipython/kernels/clingkernel/kernel.json

Now, how can I plot??
Just kidding :-)

**Comment by Coldmooon** [comment]
Hi, @zumpchke , where do you find `cling/kernel.json` ?  I just follow the instruction but can't find `cling/kernel.json`.
First, I installed `cling`  according to this link `https://root.cern.ch/drupal/content/cling-build-instructions`.
Then, I run `ipython kernelspec install cling` in terminal. I don't know where to find `cling/kernel.json`

**Comment by zumpchke** [comment]
As part of this project.
https://github.com/minrk/clingkernel/tree/master/cling

**Comment by Coldmooon** [comment]
@zumpchke 
Thank you for your quick help~~

**Comment by ebanner** [comment]
I can get it running just fine, but I'm getting extremely sparse syntax highlighting (only numbers and operators). The output of:

IPython.notebook.get_selected_cell().code_mirror.getOption('mode')

is 'clike' and I do have a clike.js in html/static/components/codemirror/mode/clike.

Any ideas?

**Comment by Vgrunert** [comment]
I can't get it to work either. I copied the folder cling with kernel.json into .ipython.kernels. cling is installed as well as "sudo jupyter-kernelspec install ~/foo/inst/bin/cling".  However when the c++ kernel startes in jupyter I get this error: "/usr/bin/python: No module named clingkernel". So I changed "clingkernel" in the kernel.json to the location of the cling executable: "~/foo/inst/bin/cling". However then I get the following error: "/usr/bin/python: No module named /home/vincent/foo/inst/bin/cling". I am really stuck. Any help is greatly appreciated.

**Comment by olegmikul** [comment]
I can't get it working. Everything installed and copied. It see C++ ok for couple seconds and then (after getting a message "adapting to protocol v4.0 for kernel ...") treats C++ code as Python code. Help, please.

**Comment by minrk** [comment]
@olegmikul you mean the highlighting is wrong, or the code execution is wrong?

**Comment by olegmikul** [comment]
Both, initially both are right, then both switch to Python mode. I will try to reproduce it on my linux VM tonight with different Linux version.

**Comment by olegmikul** [comment]
ok, sorry for the noise, mystery is solved - it is IJulia who is messing up with both Python and C++. Since the syntax of Julia and Python are close enough  I took it wrong. My apology.

**Comment by olegmikul** [comment]
after heavy unistalling and reinstalling everything it finally works. Small issue as "[IPKerlanAPP] ERROR | UNKNOWN MESSAGE TYPE: comm_open" errror, but can ignore for now. 

"Now, how can I plot??" :)

**Comment by olegmikul** [comment]
Code runs fine, but highlighting is wrong. Not a big deal, but a bit annoying. Any help ?

**Comment by JhoanDoe** [comment]
Does anyone have successfully installed this kernel in windows?, if i'm not mistaken first i need to install cling in my machine, however this is not easy task for windows users (as far as i've been reading). I'm having trouble with this since i can't find a way to install cling in my computer with windows 10 and therefore can't install the clingkernel.
 I'm a noob in this things so a detailed explanation will be apreciated.

**Comment by VladimirSokolskii** [comment]
Hi!How to fix the problem? I am newbie:)
vladimir@vladimir-HP-Pavilion-g7-Notebook-PC:~/cppkernel/clingkernel-master/cling$ sudo jupyter kernelspec install cling
[sudo] password for vladimir: 
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-kernelspec", line 7, in <module>
    from jupyter_client.kernelspecapp import KernelSpecApp
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/usr/local/lib/python3.4/dist-packages/jupyter_client/connect.py", line 21, in <module>
    import zmq
ImportError: No module named 'zmq'
vladimir@vladimir-HP-Pavilion-g7-Notebook-PC:~/cppkernel/clingkernel-master/cling$ pip install zmq
Requirement already satisfied (use --upgrade to upgrade): zmq in /home/vladimir/anaconda3/lib/python3.4/site-packages
Requirement already satisfied (use --upgrade to upgrade): pyzmq in /home/vladimir/anaconda3/lib/python3.4/site-packages (from zmq)
vladimir@vladimir-HP-Pavilion-g7-Notebook-PC:~/cppkernel/clingkernel-master/cling$

**Comment by minrk** [comment]
@VladimirSokolskii what do you get from `python -c import zmq`? It seems like something is broken.

**Comment by VladimirSokolskii** [comment]
vladimir@vladimir-HP-Pavilion-g7-Notebook-PC:~$ python -c import zmq
  File "<string>", line 1
    import
         ^
SyntaxError: invalid syntax

**Comment by VladimirSokolskii** [comment]
vladimir@vladimir-HP-Pavilion-g7-Notebook-PC:~$ python -c import zmq
  File "<string>", line 1
    import
         ^
SyntaxError: invalid syntax

**Comment by VladimirSokolskii** [comment]
vladimir@vladimir-HP-Pavilion-g7-Notebook-PC:~$ python -c import zmq
      File "<string>", line 1
        import
         ^
    SyntaxError: invalid syntax
