### ISSUE TITLE
Problem running this kernel

### ISSUE THREAD

**Issue by ricsp** [minrk/clingkernel#8]
Hi,

first of all thanks for sharing this kernel. It seems to be pretty useful.
I installed it but I cannot make it work and I am fairly new to python and Ipython.
The first time I tried I got this error:

>Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/clingkernel.py", line 13, in <module>
    from ipykernel.kernelbase import Kernel
ImportError: No module named ipykernel.kernelbase

I solved (?) it by changing
```python
from ipykernel.kernelbase import Kernel
```
with
```python
from IPython.kernel.zmq.kernelbase import Kernel
```
in clingkernel.py, but now I have this other error

>Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/clingkernel.py", line 15, in <module>
    from pexpect import replwrap, EOF
ImportError: cannot import name replwrap

I guess this has to do with some compatibilty issues.
Any chances this can be solved?
Thanks and cheers.

Riccardo

**Comment by minrk** [comment]
Yes, I wrote it against 4.0, since that's what I'm using. There's no reason for it to not work on 3.x, too. I just haven't had a chance to clean it up.
